notebook:
  image: jupyter/minimal-notebook
  command: bash -c 'pip install py2neo; start-notebook.sh --NotebookApp.allow_origin=*'
  environment:
    DOCKER: 'true'
    NEO4J_REST_URL: http://neo4j:7474/db/data/
  ports:
    - "8888:8888"
  links:
    - neo4j

neo4j:
  image: neo4j:latest
  ports:
    - "7474:7474"
  environment:
    NEO4J_AUTH: none
